工地專案管理系統/TestFirst/Models/chartMission.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestFirst.Models
{
    public class chartMission
    {
        public int fId { get; set; }
        public int fStage { get; set; }
        public int fEst_Time { get; set; }
    }
}

工地專案管理系統/TestFirst/Models/chartProject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestFirst.Models
{
    public class chartProject
    {
        public DateTime fEst_StartDate { get; set; }
        public DateTime fEst_EndDate { get; set; }
        public DateTime fReal_StartDate { get; set; }
        public DateTime fReal_EndDate { get; set; }
    }
}

工地專案管理系統/TestFirst/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestFirst.Models;

namespace TestFirst.Controllers
{
    public class ChartController : Controller
    {
        dbMyProjectEntities1 db = new dbMyProjectEntities1();
        
        // GET: Chart
        public ActionResult chartProject()
        {
            var q = from p in db.tProject
                    select p;
            List<chartProject> cp = new List<chartProject>();
            List<string> lab2 = new List<string>();
            List<decimal> val2 = new List<decimal>();
            foreach(var item in q)
            {
                var daydiff =new TimeSpan( item.fEST_EndDate.Ticks - item.fEST_StartDate.Ticks).Days;
                chartProject c = new chartProject();
                c.fEst_StartDate = item.fEST_StartDate;
                c.fEst_EndDate = item.fEST_EndDate;
                if (item.fReal_StartDate!=null)
                {
                    c.fReal_StartDate = (DateTime)item.fReal_StartDate;
                }
                if (item.fReal_EndDate != null)
                {
                    c.fReal_EndDate = (DateTime)item.fReal_EndDate;
                }
                cp.Add(c);
                lab2.Add(item.fName);
                val2.Add((decimal)item.fMoney);
            }
            ViewBag.lab2 = lab2;
            ViewBag.val2 = val2;
            return View(cp);
        }

        public ActionResult chartMission()
        {
            var q = from p in db.tMission
                    select p;
            List<chartMission> cp = new List<chartMission>();
            foreach (var item in q)
            {
                chartMission c = new chartMission();
                c.fId = item.fId;
                c.fStage = int.Parse(item.fStage);
                c.fEst_Time = int.Parse(item.fSum_Time);
                cp.Add(c);
            }
            IQueryable<IGrouping<string, string>> model = db.tMission.GroupBy(p => p.fStage,
                                                                 p=>p.fSum_Time);
            List<int> sum_EST = new List<int>();
            List<string> lab1 = new List<string>();
            List<string> lab2 = new List<string>();
            lab2.Add("0");
            foreach (var item in model)
            {
                //Console.WriteLine("----"+item.Key+"----");//debug
                lab1.Add("Stage"+item.Key);
                lab2.Add("Stage"+item.Key);
                int sum = 0;
                foreach (var item2 in item)
                {
                    sum+= int.Parse(item2);
                    Console.WriteLine(item2);
                }
                sum_EST.Add(sum);
            }
            ViewBag.lab1 = lab1;
            ViewBag.sum1 = sum_EST;
            List<int> sum_EST2 = new List<int>
            {   
                0,
                sum_EST[0],
                sum_EST[0] + sum_EST[1],
                sum_EST[0] + sum_EST[1] + sum_EST[2],
                sum_EST[0] + sum_EST[1] + sum_EST[2] + sum_EST[3]
            };
            ViewBag.lab2 = lab2;
            ViewBag.sum2 = sum_EST2;
            return View(cp);
        }

        public ActionResult chartProject_Humancost()
        {
            var q = from p in db.tProject_HumanCost
                    select p;
            List<tProject_HumanCost> cp = new List<tProject_HumanCost>();
            foreach (var item in q)
            {
                tProject_HumanCost c = new tProject_HumanCost();
                c.fId = item.fId;
                c.fProjectCode = item.fProjectCode;
                c.fLevel = item.fLevel;
                c.fSalary = item.fSalary;
                c.fNumberOfPeople = item.fNumberOfPeople;
                c.fStartDate = item.fStartDate;
                c.fEndDate = item.fEndDate;
                cp.Add(c);
            }
            //part2
            List<string> fProjectCode = new List<string>();
            foreach (var item in db.tProject_HumanCost)
            {
                if (fProjectCode.Count == 0)
                {
                    fProjectCode.Add(item.fProjectCode);
                }
                else
                {
                    if (!fProjectCode.Contains(item.fProjectCode))//職位不重複
                    {
                        fProjectCode.Add(item.fProjectCode);
                    }
                }
            }
            ViewBag.lab2 = fProjectCode;
            List<string> fLevel = new List<string>();
            foreach (var item in db.tProject_HumanCost)
            {
                if (fLevel.Count == 0)//第一筆
                {
                    fLevel.Add(item.fLevel);
                    
                }
                else
                {
                    if (!fLevel.Contains(item.fLevel))//職位不重複
                    {
                        fLevel.Add(item.fLevel);
                    }
                }
            }
            List<double> tTpa01 = new List<double>(fProjectCode.Count);
            List<double> tTpa02 = new List<double>(fProjectCode.Count);
            List<double> tTYH01 = new List<double>(fProjectCode.Count);
            List<double> tTpa03 = new List<double>(fProjectCode.Count);
            List<double> tNWT01 = new List<double>(fProjectCode.Count);
            foreach (var item in fProjectCode)
            {
                var s = from p in db.tProject_HumanCost
                        where p.fProjectCode == item
                        select p;
                switch (item)
                {
                    case "TPA01":
                        f3(tTpa01, s);
                        break;
                    case "TPA02":
                        f3(tTpa02, s);
                        break;
                    case "TYH01":
                        f3(tTYH01, s);
                        break;
                    case "TPA03":
                        f3(tTpa03, s);
                        break;
                    case "NWT01":
                        f3(tNWT01, s);
                        break;
                    default:
                        break;
                }
                
            }
            void f3(List<double> p1,IQueryable<tProject_HumanCost> s)
            {
                foreach (var item2 in fLevel)
                {
                    var s2 = from p2 in s
                             where p2.fLevel == item2
                             select p2;
                    foreach (var item3 in s2)
                    {
                        p1.Add((double)item3.fSalary * item3.fNumberOfPeople);
                    }
                }
            }
            ViewBag.fProjectCode = fProjectCode;
            ViewBag.tTpa01 = tTpa01;
            ViewBag.tTpa02 = tTpa02;
            ViewBag.tTYH01 = tTYH01;
            ViewBag.tTpa03 = tTpa03;
            ViewBag.tNWT01 = tNWT01;

            Console.WriteLine("sss");
            return View(cp);
        }   
    }
}

工地專案管理系統/TestFirst/Views/Chart/chartMission.cshtml
@model IEnumerable<TestFirst.Models.chartMission>
@{
    ViewBag.Title = "chartMission";
    
}

<link href="../Content/bootstrap.min.css" rel="stylesheet" />
<script src="../Scripts/Chart.min.js"></script>
<script src="../Assets/js/Colors.js"></script>
<script src="../Assets/js/Utility.js"></script>

<br />
<div>
    <h4 style="font-weight:bold">
        施工日數表
        @Html.ActionLink("專案時程圖", "chartProject", "Chart", new { }, new { @class = "btn btn-secondary" })
        @Html.ActionLink("施工日數表", "chartMission", "Chart", new { }, new { @class = "btn btn-info" })
        @Html.ActionLink("員工薪資表", "chartProject_humancost", "Chart", new { }, new { @class = "btn btn-secondary" })
    </h4>
</div>

<div class="container">
    <div class="jumbotron alert-success">
        <h2>各階段施工日數表</h2>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <canvas id="barChart1"></canvas>
    </div>
    <hr />
    <div class="container">
        <div class="jumbotron alert-success">
            <h2>累積施工日數表</h2>
        </div>
        <canvas id="myChart"></canvas>
    </div>
    
</div>
@{
    //----------------------C#  Part1----------------------------
    var jsonlab1 = Json.Encode(ViewBag.lab1);
    var jsondata1 = Json.Encode(ViewBag.sum1);
    //----------------------C#  Part2----------------------------
    var jsonlab2 = Json.Encode(ViewBag.lab2);
    var jsondata2 = Json.Encode(ViewBag.sum2);
}
<script>
    var ctx = document.getElementById("barChart1");
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: @Html.Raw(jsonlab1),
            datasets: [{
                label: '各階段施工日數表',
                data: @Html.Raw(jsondata1),
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }],
            }
        }
    });
    var ctx = document.getElementById("myChart");
    var chart = new Chart(ctx, {
        type: "line",
        data: {
            labels:@Html.Raw(jsonlab2),
            datasets: [{
                label: "",
                data: @Html.Raw(jsondata2),
                fill: false,
                backgroundColor: 'rgba(255,165,0,0.3)',
                borderColor: 'rgb(255,165,0)',
                pointStyle: "circle",
                pointBackgroundColor: 'rgb(0,255,0)',
                pointRadius: 5,
                pointHoverRadius: 10,
            }]
        },
        options: {
            responsive: true,
            title: {
                display: true,
                fontSize: 26,
                text: '累積施工日數表'
            },
            tooltips: {
                mode: 'point',
                intersect: true,
            },
            legend: {
                position: 'bottom',
                labels: {
                    fontColor: 'black',
                }
            }
        }
    });
</script>
<br />

工地專案管理系統/TestFirst/Views/Chart/chartProject.cshtml
@model IEnumerable<TestFirst.Models.chartProject>

@{
    ViewBag.Title = "chartProject";
}

<script src="../Scripts/Chart.min.js"></script>

<br />
<div>
    <h4 style="font-weight:bold">
        專案時程圖
        @Html.ActionLink("專案時程圖", "chartProject", "Chart", new { }, new { @class = "btn btn-info" })
        @Html.ActionLink("施工日數表", "chartMission", "Chart", new { }, new { @class = "btn btn-secondary" })
        @Html.ActionLink("員工薪資表", "chartProject_humancost", "Chart", new { }, new { @class = "btn btn-secondary" })
    </h4>

</div>

<br />
<div class="container">
    <div class="jumbotron alert-success">
        <h2>Gantt 專案時程圖</h2>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <canvas id="myChart"></canvas>
    </div>
</div>
<hr />
<div class="container">
    <div class="jumbotron alert-success">
        <h2>專案金額比率</h2>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <canvas id="doughnut-chart"></canvas>
    </div>
</div>

@{ 
    //-----------part1-------------

    //-----------part2-------------
    var jsonLab2 = Json.Encode(ViewBag.lab2);
    var jsonVal2 = Json.Encode(ViewBag.val2);
}
<script>
    var barOptions_stacked = {
        hover: {
            animationDuration: 10
        },
        scales: {
            xAxes: [{
                label: "Duration",
                ticks: {
                    beginAtZero: true,
                    fontFamily: "'Open Sans Bold', sans-serif",
                    fontSize: 11
                },
                scaleLabel: {
                    display: false
                },
                gridLines: {
                },
                stacked: true
            }],
            yAxes: [{
                gridLines: {
                    display: false,
                    color: "#fff",
                    zeroLineColor: "#fff",
                    zeroLineWidth: 0
                },
                ticks: {
                    fontFamily: "'Open Sans Bold', sans-serif",
                    fontSize: 11
                },
                stacked: true
            }]
        },
        legend: {
            display: false
        },
    };

    var ctx = document.getElementById("myChart");
    //TODO...
    var myChart = new Chart(ctx, {
        type: 'horizontalBar',
        data: {
            labels: ["1", "2", "3", "4","5"],

            datasets: [{
                data: [50, 150, 300, 200, 450],//start
                backgroundColor: "rgba(63,103,126,0)",
                hoverBackgroundColor: "rgba(50,90,100,0)"

            }, {
                data: [100, 100, 200, 200, 100],//duration
                backgroundColor: ['red', 'green', 'blue', 'yellow'],
            }]
        },
        options: barOptions_stacked,
    });

    //// this part to make the tooltip only active on your real dataset
    //var originalGetElementAtEvent = myChart.getElementAtEvent;
    //myChart.getElementAtEvent = function (e) {
    //    return originalGetElementAtEvent.apply(this, arguments).filter(function (e) {
    //        return e._datasetIndex === 1;
    //    });
    //}
    new Chart(document.getElementById("doughnut-chart"), {
        type: 'doughnut',
        data: {
            labels: @Html.Raw(jsonLab2),
            datasets: [
                {
                    label: "Population (millions)",
                    backgroundColor: ["#3e95cd", "#8e5ea2", "#3cba9f", "#e8c3b9", "#c45850"],
                    data: @Html.Raw(jsonVal2)
                }
            ]
        },
        options: {
            title: {
                display: true,
                text: '專案金額比率'
            }
        }
    });

</script>

工地專案管理系統/TestFirst/Views/Chart/chartProject_Humancost.cshtml
@model IEnumerable<TestFirst.tProject_HumanCost>

@{
    ViewBag.Title = "chartProject_Humancost";
}
@*<script src="../Scripts/Chart.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>


<br />
<div>
    <h4 style="font-weight:bold">
        員工薪資表
        @Html.ActionLink("專案時程圖", "chartProject", "Chart", new { }, new { @class = "btn btn-secondary" })
        @Html.ActionLink("施工日數表", "chartMission", "Chart", new { }, new { @class = "btn btn-secondary" })
        @Html.ActionLink("員工薪資表", "chartProject_humancost", "Chart", new { }, new { @class = "btn btn-info" })
    </h4>
</div>
@*各職位新資HTML*@
<hr />
<div class="container">
    <div class="jumbotron alert-success">
        <h2>各職位新資</h2>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <canvas id="barChart"></canvas>
    </div>
</div>
<hr />


@*各職位薪資C#運算*@
@{

    List<string> fLevel = new List<string>();
    List<int> fSalary = new List<int>();
    foreach (var item in Model)
    {

        if (fLevel.Count == 0)//第一筆
        {
            fLevel.Add(item.fLevel);
            fSalary.Add((int)item.fSalary);
        }
        else
        {
            if (!fLevel.Contains(item.fLevel))//職位不重複
            {
                fLevel.Add(item.fLevel);
                fSalary.Add((int)item.fSalary);
            }

        }
    }
    var labfLevel = Json.Encode(fLevel);
    var labfSalary = Json.Encode(fSalary);


}

@*各職位新資之BAR圖Javascript*@
<script>

    var ctx = document.getElementById("barChart");
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels:@Html.Raw(labfLevel),
            datasets: [{
                label: '',
                data: @Html.Raw(labfSalary),
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            },
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }],
            }
        }
    });
</script>

@*--------------------------Part 2-------------------------------*@

@*專案人事支出人事支出C#部分*@
@{






    int pindex = 0;

    //List<int> tTpa01 = new List<int> { 1, 2, 3, 4, 5 };
    //List<int> tTpa02 = new List<int> { 2, 4, 3, 1, 5 };
    //List<int> tTpa03 = new List<int> { 5, 3, 2, 4, 1 };
    //List<int> tTYH01 = new List<int> { 1, 5, 3, 4, 2 };
    //List<int> tNWT01 = new List<int> { 3, 4, 1, 2, 5 };
    var jsonfProjectCode0 = Json.Encode(ViewBag.fProjectCode[0]);
    var jsonfProjectCode1 = Json.Encode(ViewBag.fProjectCode[1]);
    var jsonfProjectCode2 = Json.Encode(ViewBag.fProjectCode[2]);
    var jsonfProjectCode3 = Json.Encode(ViewBag.fProjectCode[3]);
    var jsonfProjectCode4 = Json.Encode(ViewBag.fProjectCode[4]);

    var jsontTpa01 = Json.Encode(@ViewBag.tTpa01);
    var jsontTpa02 = Json.Encode(@ViewBag.tTpa02);
    var jsontTpa03 = Json.Encode(@ViewBag.tTpa03);
    var jsontTYH01 = Json.Encode(@ViewBag.tTYH01);
    var jsontNWT01 = Json.Encode(@ViewBag.tNWT01);
}



@*專案人事支出人事支出HTML部分*@
<div class="container">
    <div class="jumbotron alert-success">
        <h2>專案人事支出</h2>
    </div>
    <div class="dropdown">
        <div id="divProject" class="btn-group" role="group" aria-label="Basic example">
            @foreach (var item in @ViewBag.fProjectCode)
            {
                pindex++;
                string sid = "btn" + pindex;
                <input type="button" class="btn btn-info" value=@item id=@sid />
            }
        </div>

    </div>
    <div class="col-md-8 col-md-offset-2">
        <canvas id="radarChart"></canvas>
    </div>
</div>



@*專案人事支出人事支出Javascript畫圖部分*@
<script>

    var value1
    var valLab

    var ctx = document.getElementById('radarChart')
    f1()
    document.querySelector("#btn1").addEventListener("click", f1)
    function f1() {
        //alert("111");
        value1 =@Html.Raw(jsontTpa01)
            valLab = @Html.Raw(jsonfProjectCode0)
        drow2();
    }
    document.querySelector("#btn2").addEventListener("click", f2)
    function f2() {
        value1=@Html.Raw(jsontTpa02)
            valLab = @Html.Raw(jsonfProjectCode1)
        drow2();
    }
    document.querySelector("#btn3").addEventListener("click", f3)
    function f3() {
        value1=@Html.Raw(jsontTYH01)
            valLab = @Html.Raw(jsonfProjectCode2)
        drow2();
    }
    document.querySelector("#btn4").addEventListener("click", f4)
    function f4() {
        value1=@Html.Raw(jsontTpa03)
            valLab = @Html.Raw(jsonfProjectCode3)
        drow2();
    }
    document.querySelector("#btn5").addEventListener("click", f5)
    function f5() {
        value1=@Html.Raw(jsontNWT01)
            valLab = @Html.Raw(jsonfProjectCode4)
        drow2();
    }
    function drow2() {
        var chart = new Chart(ctx, {
        type: 'radar',
        data: {
            labels: @Html.Raw(labfLevel),
            datasets: [{
                label: valLab,
                data: value1,
                backgroundColor: 'rgba(173,255,47, 0.5)',
                borderColor: 'rgb(0,0,0)',
                pointStyle: 'circle',
                pointBackgroundColor: 'rgb(0,0,255)',
                pointRadius: 1,
                pointHoverRadius: 0,
            }]
        },
        options: {
            responsive: true,
            legend: {
                position: 'top',
                labels: {
                    fontColor: 'black',
                    fontSize: 24
                }
            },
            title: {
                display: true,
                text: '專案人事支出(職位*人數)',
                fontSize: 26,
            },
            scale: {
                ticks: {
                    beginAtZero: true
                },
                pointLabels: {
                    fontSize: 20
                },
            },
        }
    });
    }


</script>