工地專案管理系統/TestFirst/Controllers/工程管理Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestFirst.Models;
using TestFirst.Viewmodel;
using PagedList;

namespace TestFirst.Controllers
{
    // 工程管理的Controller
    public class 工程管理Controller : Controller
    {
        dbMyProjectEntities1 db = new dbMyProjectEntities1();
        public ActionResult 管理首頁(CAdvanceQueryCondition selectdata,string order="")
        {
            if (Session["UserId"].ToString().Substring(0,1)=="4")
            {
                return RedirectToAction("首頁", "Home", new { });
            }
            IQueryable<tMission> table=db.tMission.Select(p => p);
            if (order=="")
            {
            }
            else if (order=="code")
            {
                if (Session["order"] ==null)
                {
                    table =table.OrderBy(p => p.fCode);
                    Session["order"] = "code";
                }
                else if(Session["order"]!=null && Session["order"].ToString()=="code")
                {
                    table = table.OrderByDescending(p => p.fCode);
                    Session["order"] = "codeDes";
                }
                else
                {
                    table = table.OrderBy(p => p.fCode);
                    Session["order"] = "code";
                }
                
            }
            else if (order=="date1")
            {
                if (Session["order"] == null)
                {
                    table = table.OrderBy(p => p.fEST_Time);
                    Session["order"] = "date1";
                }
                else if (Session["order"] != null && Session["order"].ToString() == "date1")
                {
                    table = table.OrderByDescending(p => p.fEST_Time);
                    Session["order"] = "date1Des";
                }
                else
                {
                    table = table.OrderBy(p => p.fEST_Time);
                    Session["order"] = "date1";
                }

            }
            else if (order=="date2")
            {
                if (Session["order"] == null)
                {
                    table = table.OrderBy(p =>p.fSum_Time);
                    Session["order"] = "date2";
                }
                else if (Session["order"] != null && Session["order"].ToString() == "date2")
                {
                    table = table.OrderByDescending(p => p.fSum_Time);
                    Session["order"] = "date2Des";
                }
                else
                {
                    table = table.OrderBy(p => p.fSum_Time);
                    Session["order"] = "date2";
                }
            }
            else if (order=="date3")
            {
                if (Session["order"] == null)
                {
                    table = table.OrderBy(p => p.fReal_Time);
                    Session["order"] = "date3";
                }
                else if (Session["order"] != null && Session["order"].ToString() == "date3")
                {
                    table = table.OrderByDescending(p => p.fReal_Time);
                    Session["order"] = "date3Des";
                }
                else
                {
                    table = table.OrderBy(p => p.fReal_Time);
                    Session["order"] = "date3";
                }
            }
            else if (order=="money")
            {
                if (Session["order"] == null)
                {
                    table = table.OrderBy(p => p.fPayment);
                    Session["order"] = "money";
                }
                else if (Session["order"] != null && Session["order"].ToString() == "money")
                {
                    table = table.OrderByDescending(p => p.fPayment);
                    Session["order"] = "moneyDes";
                }
                else
                {
                    table = table.OrderBy(p => p.fPayment);
                    Session["order"] = "money";
                }
            }
           
            ViewBag.stage = table.Select(p => p.fStage).Distinct();
            ViewBag.Year = table.Select(p => p.fEST_Time.Substring(0, 4)).Distinct();

            if (!string.IsNullOrEmpty(selectdata.txtName))  //工程名稱
            {
                table = table.Where(p => p.fName.Contains(selectdata.txtName));
            }
            if (!string.IsNullOrEmpty(selectdata.txtStage)) //工程階段
            {
                table = table.Where(p => p.fStage.Contains(selectdata.txtStage));
            }
            if (!string.IsNullOrEmpty(selectdata.txtCode))  //工程代號
            {
                table = table.Where(p => p.fCode.Contains(selectdata.txtCode));
            }
            if (!string.IsNullOrEmpty(selectdata.txtChargeMan))//負責人
            {
                table = table.Where(p => p.fChargeMan.Contains(selectdata.txtChargeMan));
            }

            if (!string.IsNullOrEmpty(selectdata.txtDaystart) && !string.IsNullOrEmpty(selectdata.txtDayEnd))//開工日期
            {
                var searchstartday = selectdata.txtDaystart.Replace("/", "");
                var searchendday = selectdata.txtDayEnd.Replace("/", "");
                table = table.Where(p => (p.fEST_Time.CompareTo(searchstartday) >= 0 && p.fEST_Time.CompareTo(searchendday) <= 0));

            }
            if (!string.IsNullOrEmpty(selectdata.txtCompleteDayStart) && !string.IsNullOrEmpty(selectdata.txtCompleteDayEnd))//完工日期
            {
                var searchstartday = selectdata.txtCompleteDayStart.Replace("/", "");
                var searchendday = selectdata.txtCompleteDayEnd.Replace("/", "");
                table = table.Where(p => (p.fReal_Time.CompareTo(searchstartday) >= 0 && p.fReal_Time.CompareTo(searchendday) <= 0));

            }
            if (!string.IsNullOrEmpty(selectdata.txtPaymentStart) && !string.IsNullOrEmpty(selectdata.txtPaymentEnd))// 工程金額
            {
                decimal? start = Convert.ToDecimal(selectdata.txtPaymentStart);
                decimal? end = Convert.ToDecimal(selectdata.txtPaymentEnd);
                table = table.Where(p => (p.fPayment >= start && p.fPayment <= end));
            }
         
            return View(table);
        }
        // AJAX_工程項目的狀態檢查(回傳個狀態的工程列表)
        public ActionResult AJAX_Check()
        {
            List<List<string>> list = new List<List<string>>() ;
            list.Add(db.tMission_SignOff.Where(p => p.fStatus == "簽核完畢").Select(p => p.fMissionCode).ToList());
            list.Add(db.tMission_SignOff.Where(p => p.fStatus == "已駁回").Select(p => p.fMissionCode).ToList());
            list.Add(db.tMission_SignOff.Where(p => p.fStatus == "待主管核准").Select(p => p.fMissionCode).ToList());
            list.Add(db.tMission_SignOff.Where(p => p.fStatus == "完工待審").Select(p => p.fMissionCode).ToList());
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public ActionResult 新增專案()
        {
            return View();
        }
        [HttpPost]
        public ActionResult 新增專案(tMission theproject)
        {
            string changedate=theproject.fEST_Time.Substring(0,4)+"/"+ theproject.fEST_Time.Substring(4,2)+"/"+theproject.fEST_Time.Substring(6,2);
           
            var countday = DateTime.Parse(changedate);

            theproject.fReal_Time = (countday.AddDays(Convert.ToDouble(theproject.fSum_Time))).ToString("yyyy/MM/dd").Replace("/","");
            db.tMission.Add(theproject);
           
            db.SaveChanges();
            return RedirectToAction("管理首頁");
        }
        public ActionResult 編輯專案(int fId)
        {
            tMission myproject = (new dbMyProjectEntities1()).tMission.FirstOrDefault(p => p.fId == fId);
            if (myproject == null)
                return RedirectToAction("管理首頁");
            return View(myproject);
          
        }
        [HttpPost]
        public ActionResult 編輯專案(tMission changproject)
        {
            
            tMission olddata = db.tMission.FirstOrDefault(t => t.fId == changproject.fId);
            if (olddata != null)
            {
                olddata.fName = changproject.fName;
                //olddata.fProjectCode = changproject.fProjectCode;
                olddata.fStage = changproject.fStage;
                olddata.fCode = changproject.fCode;
                olddata.fEST_Time = changproject.fEST_Time;
                olddata.fSum_Time = changproject.fSum_Time;

                string changedate = changproject.fEST_Time.Substring(0, 4) + "/" + changproject.fEST_Time.Substring(4, 2) + "/" + changproject.fEST_Time.Substring(6, 2);
                var countday = DateTime.Parse(changedate);
                olddata.fReal_Time = changproject.fReal_Time = (countday.AddDays(Convert.ToDouble(changproject.fSum_Time))).ToString("yyyy/MM/dd").Replace("/", "");

                // olddata.fComplete = changproject.fComplete;
                olddata.fChargeMan = changproject.fChargeMan;
                //olddata.fPhone = changproject.fPhone;
                olddata.fPS = changproject.fPS;
                // olddata.fPayment = changproject.fPayment;
                db.SaveChanges();
            }
            return RedirectToAction("管理首頁");

        }


        //public ActionResult 刪除專案(int fId)
        //{
        //    dbMyProjectEntitiesModel db = new dbMyProjectEntitiesModel();
        //    tMission theproject = db.tMission.FirstOrDefault(p => p.fId == fId);
        //    if (theproject != null)
        //    {
        //        db.tMission.Remove(theproject);
        //        db.SaveChanges();
        //    }
            
        //    return RedirectToAction("管理首頁");
        //}


        public ActionResult 日報列表(CForreport data,string date="")
        {
            var table = (new dbMyProjectEntities1()).tMissionDetail.Select(p => p);
           
            ViewBag.Year = table.Select(p => p.fToday.Substring(0, 4)).Distinct();

工地專案管理系統/TestFirst/Views/工程管理/新增專案.cshtml
@model TestFirst.tMission

@{
    ViewBag.Title = "新增專案";
}

<br />
<h2>新增專案</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.fProjectCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fProjectCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fProjectCode, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fStage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fStage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fStage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fEST_Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fEST_Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fEST_Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fSum_Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fSum_Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fSum_Time, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.fReal_Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fReal_Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fReal_Time, "", new { @class = "text-danger" })
            </div>
        </div>*@
 
       @*<div class="form-group">
            @Html.LabelFor(model => model.fComplete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fComplete, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fComplete, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fChargeMan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fChargeMan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fChargeMan, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.fPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fPhone, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fPS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fPS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fPS, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.fPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fPayment, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-primary" />
               @Html.ActionLink("取消","管理首頁","工程管理",null,new { @class="btn btn-danger"})           
            </div>
        </div>
    </div>
}


@section scripts{
<script>
    $('.theli').hide();
</script>
    }

工地專案管理系統/TestFirst/Views/工程管理/新增日報.cshtml
@model TestFirst.tMissionDetail

@{
    ViewBag.Title = "新增日報";
}

<br />
<br />




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>新增日報</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*材料*@
        @*<div class="form-group">
            @Html.LabelFor(model => model.fMaterial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fMaterial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fMaterial, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.fChargeMan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fChargeMan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fChargeMan, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fWorkers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fWorkers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fWorkers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fWeather, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fWeather, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fWeather, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.fToday, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fToday, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fToday, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.fPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fPhoto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fPhoto, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fPS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fPS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fPS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-primary" />
                @Html.ActionLink("取消","日報列表","工程管理",null,new { @class="btn btn-danger"})
            </div>
        </div>
    </div>

}


@section scripts{
    <script>
        $('.theli').hide();
    </script>
}

工地專案管理系統/TestFirst/Views/工程管理/日報列表.cshtml
@model IEnumerable<TestFirst.tMissionDetail>
@{
    ViewBag.Title = "日報列表";
}
<br />
@using (Html.BeginForm())
{
<h4 style="font-weight:bold">
    工程管理系統
    @Html.ActionLink("工程列表", "管理首頁", "工程管理", null, new { @class = "btn btn-secondary" })
    @Html.ActionLink("日報列表", "日報列表", "工程管理", null, new { @class = "btn btn-info" })

</h4>
    <hr />
    <body>
        <div>
            <fieldset class="clearfix" style="border:2px solid #DDDDDD; padding:10px; border-radius:20px;" id="Search">
                <legend class="container-sm">進階查詢</legend>
                <div class="container-sm">
                    <label>施工項目 : </label> @Html.TextBox("projName", null, new { @class = "form-control-sm" })
                    <label>年度 : </label>
                    <select name="projYear" id="TheYear" class="custom-select">
                        @{
                            foreach (var item in ViewBag.Year)
                            {
                                <option value="@item">@item</option>
                            }
                        }
                    </select>
                    <br>
                    <label>工程代號 : </label> @Html.TextBox("txtCode", null, new { @class = "form-control-sm" })
                    <label>月報 : </label>
                    <select name="projMouth" id="TheMouth" class="custom-select">
                        @{
                            foreach (var item in ViewBag.Mouth)
                            {
                                <option value="@item">@item</option>
                            }
                        }
                    </select>
                    <br>
                    <label>負責人員 : </label> @Html.TextBox("projChargeMan", null, new { @class = "form-control-sm" })
                    <label>週報 : </label>
                    <select name="projWeekend" class="custom-select">
                        <option value=""></option>
                        <option value="第一週">第一週</option>
                        <option value="第二週">第二週</option>
                        <option value="第三週">第三週</option>
                        <option value="第四週">第四週</option>
                        <option value="第五週">第五週</option>
                    </select>
                    <br /><br />
                    <label>日期區間 : </label> @Html.TextBox("projDayStart", null, new { @class = "form-control-sm" })
                    ~@Html.TextBox("projDayEnd", null, new { @class = "form-control-sm" })
                    <br /><br />
                    <input type="submit" value="查詢" class="btn btn-outline-primary" />
                </div>
            </fieldset>
        </div>

        <br />
        <p>

            @Html.ActionLink("新增日報", "新增日報", "工程管理", null, new { @class = "btn btn-primary" })
            <button type="button" class="btn btn-info" style="float:right" onclick="hidding()">Search</button>

        </p>


        <table class="table table-bordered table-striped ">
            <tr style="background-color:lightgray">
                <th>
                    專案代號
                </th>
                <th>
                    工程項目
                </th>
                <th>
                    工地負責人
                </th>
                <th>
                    日期<img src="~/img/tri.png" style="width:12px;float:right;margin-top:5px" onclick="orderby_date()" />
                </th>
                <th>
                    工作人數
                </th>
                <th>
                    天氣
                </th>
                <th>
                    備 註
                </th>
                <th>
                    編輯
                </th>
                <th>
                    刪除
                </th>
                <th>
                    工程照片
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.fCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fChargeMan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fToday)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fWorkers)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fWeather)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fPS)
                    </td>
                    <td>
                        @Html.ActionLink("編輯", "編輯日報", "工程管理", new { fId = item.fId }, new { @class = "btn btn-info" })
                    </td>
                    <td>
                        @Html.ActionLink("刪除", "刪除日報", "工程管理", new { fId = item.fId }, new { @class = "btn btn-danger", onclick = "return confirm('確定要刪除嗎?')" })
                    </td>
                    <td>
                        @Html.ActionLink("上傳照片", "Photos_new", "Home", new { name = item.fName }, new { @class = "btn btn-warning" })

                    </td>
                </tr>
            }


        </table>


        @section scripts{
            <script>
                $('.theli').hide();
                var flag = false;
                $('#Search').hide();
                function hidding() {
                    if (flag == false) {
                        $('#Search').show();
                        flag = true;
                    }
                    else {
                        $('#Search').hide();
                        flag = false;
                    }

                }
                function orderby_date() {
                    window.location.href = "../工程管理/日報列表?date=fToday";
                }

            </script>
        }
    </body>
}

工地專案管理系統/TestFirst/Views/工程管理/編輯日報.cshtml
@model TestFirst.tMissionDetail

@{
    ViewBag.Title = "編輯日報";
}

<br />

<h2>編輯日報</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.fId)

        <div class="form-group">
            @Html.LabelFor(model => model.fCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.fMaterial, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fMaterial, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fMaterial, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fChargeMan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fChargeMan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fChargeMan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fWorkers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fWorkers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fWorkers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fWeather, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fWeather, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fWeather, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.fToday, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fToday, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fToday, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.fPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fPhoto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fPhoto, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.fPS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fPS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fPS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("取消", "日報列表", "工程管理", new { txtcode = Model.fCode }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>

}


@section scripts{
    <script>
        $('.theli').hide();
    </script>
}